-- ============================================================
-- 세모플 0029 — AI 도구 확장 시드: 82종 추가 (80 → 163)
-- (0001~0028 실행된 DB에 이어 실행 · 멱등 — on conflict do nothing)
--
-- 지식 기반 선별(2026-01) — 기존 등재와 중복 없음. 상세 판단 필드(enter_text·strength)는
-- 정적 시드(0003 재생성분)와 프론트 데이터에 있으며, 원격 행은 기본 컬럼만 갖는다(0006과 동일 관례).
-- URL 오류는 월간 healthcheck가 이슈로 보고 → 콘솔 편집기로 정정.
-- ============================================================

insert into public.platforms (id, name, category_id, region, url, blurb, is_new) values
  ('deepseek', 'DeepSeek', 'ai_chat', 'overseas', 'https://chat.deepseek.com', '추론 특화 오픈 모델 기반의 무료 범용 AI 챗봇.', true),
  ('qwen-chat', 'Qwen Chat', 'ai_chat', 'overseas', 'https://chat.qwen.ai', '알리바바 Qwen 모델 기반의 다국어 AI 챗봇.', true),
  ('poe', 'Poe', 'ai_chat', 'overseas', 'https://poe.com', 'GPT·Claude 등 여러 AI 모델을 한 곳에서 골라 쓰는 허브.', true),
  ('meta-ai', 'Meta AI', 'ai_chat', 'overseas', 'https://www.meta.ai', '메타 Llama 모델 기반의 무료 AI 어시스턴트.', true),
  ('kimi', 'Kimi', 'ai_chat', 'overseas', 'https://www.kimi.com', '긴 문서 이해에 강한 문샷AI의 AI 챗봇.', true),
  ('pi-ai', 'Pi', 'ai_chat', 'overseas', 'https://pi.ai', '대화 감성에 특화된 개인 비서형 AI 챗봇.', true),
  ('adot', '에이닷', 'ai_chat', 'domestic', 'https://adot.ai', 'SK텔레콤의 한국어 AI 개인 비서(통화 요약·일정 관리).', true),
  ('quillbot', 'QuillBot', 'ai_writing', 'overseas', 'https://quillbot.com', '문장 바꿔쓰기·요약·문법 교정을 한 번에 하는 영어 글쓰기 도구.', true),
  ('wordtune', 'Wordtune', 'ai_writing', 'overseas', 'https://www.wordtune.com', '문장의 톤·길이를 다듬어 주는 영어 리라이팅 도구.', true),
  ('rytr', 'Rytr', 'ai_writing', 'overseas', 'https://rytr.me', '템플릿 기반으로 카피·블로그 초안을 빠르게 뽑는 저가형 글쓰기 AI.', true),
  ('languagetool', 'LanguageTool', 'ai_writing', 'overseas', 'https://languagetool.org', '30여 개 언어를 지원하는 문법·맞춤법 교정기.', true),
  ('beautiful-ai', 'Beautiful.ai', 'ai_writing', 'overseas', 'https://www.beautiful.ai', '슬라이드 레이아웃을 자동 정돈해 주는 AI 발표자료 도구.', true),
  ('pitch', 'Pitch', 'ai_writing', 'overseas', 'https://pitch.com', '팀 협업형 발표자료 제작 도구(AI 초안 생성 지원).', true),
  ('napkin-ai', 'Napkin AI', 'ai_writing', 'overseas', 'https://www.napkin.ai', '글을 붙여넣으면 도식·다이어그램을 자동 생성하는 도구.', true),
  ('imagefx', 'Google ImageFX', 'ai_image', 'overseas', 'https://labs.google/fx', '구글 Imagen 모델 기반의 무료 이미지 생성 실험 도구.', true),
  ('krea', 'Krea', 'ai_image', 'overseas', 'https://www.krea.ai', '실시간 캔버스·업스케일을 갖춘 이미지·영상 생성 스튜디오.', true),
  ('playground-ai', 'Playground', 'ai_image', 'overseas', 'https://playground.com', '로고·포스터 등 그래픽 디자인 특화 이미지 생성 도구.', true),
  ('freepik-ai', 'Freepik AI', 'ai_image', 'overseas', 'https://www.freepik.com/ai', '스톡 이미지 서비스 프리픽의 생성·편집 AI 모음.', true),
  ('clipdrop', 'Clipdrop', 'ai_image', 'overseas', 'https://clipdrop.co', '배경 제거·조명 보정·업스케일 등 이미지 편집 AI 모음.', true),
  ('magnific', 'Magnific', 'ai_image', 'overseas', 'https://magnific.ai', '디테일을 되살리는 고품질 AI 업스케일러.', true),
  ('ms-designer', 'Microsoft Designer', 'ai_image', 'overseas', 'https://designer.microsoft.com', 'MS의 무료 AI 디자인·이미지 생성 도구.', true),
  ('looka', 'Looka', 'ai_image', 'overseas', 'https://looka.com', '브랜드명만 넣으면 로고·브랜드 킷을 만들어 주는 AI.', true),
  ('kittl', 'Kittl', 'ai_image', 'overseas', 'https://www.kittl.com', '티셔츠·라벨 등 상업 디자인 특화 AI 디자인 툴.', true),
  ('pixlr', 'Pixlr', 'ai_image', 'overseas', 'https://pixlr.com', '브라우저에서 쓰는 포토샵 대체형 AI 사진 편집기.', true),
  ('lasco', '라스코 AI', 'ai_image', 'domestic', 'https://lasco.ai', '한국어 UI로 쓰는 국내 이미지 생성 AI 스튜디오.', true),
  ('google-flow', 'Google Flow (Veo)', 'ai_video', 'overseas', 'https://labs.google/flow', '구글 Veo 모델로 장면을 이어 붙이는 AI 영상 제작 도구.', true),
  ('hailuo', 'Hailuo AI', 'ai_video', 'overseas', 'https://hailuoai.video', '미니맥스의 텍스트·이미지 기반 영상 생성 AI.', true),
  ('vidu', 'Vidu', 'ai_video', 'overseas', 'https://www.vidu.com', '캐릭터 일관성을 유지하는 텍스트→영상 생성 AI.', true),
  ('opusclip', 'OpusClip', 'ai_video', 'overseas', 'https://www.opus.pro', '긴 영상을 쇼츠·릴스용 클립으로 잘라 주는 AI.', true),
  ('invideo', 'InVideo', 'ai_video', 'overseas', 'https://invideo.io', '프롬프트로 내레이션 포함 영상을 만드는 AI 영상 제작기.', true),
  ('fliki', 'Fliki', 'ai_video', 'overseas', 'https://fliki.ai', '글을 AI 음성 내레이션 영상으로 바꿔 주는 도구.', true),
  ('veed', 'VEED', 'ai_video', 'overseas', 'https://www.veed.io', '자막·번역·녹화까지 되는 브라우저 영상 편집기.', true),
  ('d-id', 'D-ID', 'ai_video', 'overseas', 'https://www.d-id.com', '사진 한 장으로 말하는 아바타 영상을 만드는 AI.', true),
  ('colossyan', 'Colossyan', 'ai_video', 'overseas', 'https://www.colossyan.com', '교육·사내 영상용 AI 아바타 프레젠터 제작 도구.', true),
  ('playht', 'PlayHT', 'ai_audio', 'overseas', 'https://play.ht', '다국어 AI 음성 합성·클로닝 서비스.', true),
  ('speechify', 'Speechify', 'ai_audio', 'overseas', 'https://speechify.com', '문서·웹페이지를 자연스러운 음성으로 읽어 주는 TTS.', true),
  ('lalal-ai', 'LALAL.AI', 'ai_audio', 'overseas', 'https://www.lalal.ai', '음원에서 보컬·악기를 분리하는 스템 분리 AI.', true),
  ('krisp', 'Krisp', 'ai_audio', 'overseas', 'https://krisp.ai', '통화·회의 소음을 실시간 제거하는 AI 오디오 필터.', true),
  ('aiva', 'AIVA', 'ai_audio', 'overseas', 'https://www.aiva.ai', '영상·게임용 배경음악을 작곡하는 AI.', true),
  ('mubert', 'Mubert', 'ai_audio', 'overseas', 'https://mubert.com', '로열티 걱정 없는 스트리밍형 AI 음악 생성 서비스.', true),
  ('soundraw', 'Soundraw', 'ai_audio', 'overseas', 'https://soundraw.io', '길이·분위기를 지정해 BGM을 만드는 AI 작곡 도구.', true),
  ('resemble', 'Resemble AI', 'ai_audio', 'overseas', 'https://www.resemble.ai', '기업용 음성 클로닝·더빙 AI 플랫폼.', true),
  ('jetbrains-ai', 'JetBrains AI', 'ai_code', 'overseas', 'https://www.jetbrains.com/ai', 'IntelliJ 등 JetBrains IDE에 내장된 AI 코딩 어시스턴트.', true),
  ('amazon-q', 'Amazon Q Developer', 'ai_code', 'overseas', 'https://aws.amazon.com/q/developer', 'AWS 특화 AI 코딩·운영 어시스턴트.', true),
  ('tabnine', 'Tabnine', 'ai_code', 'overseas', 'https://www.tabnine.com', '프라이버시 중심의 온프레미스 지원 AI 코드 자동완성.', true),
  ('cody', 'Sourcegraph Cody', 'ai_code', 'overseas', 'https://sourcegraph.com/cody', '대형 코드베이스 검색과 결합한 AI 코딩 어시스턴트.', true),
  ('openai-codex', 'OpenAI Codex', 'ai_code', 'overseas', 'https://openai.com/codex', '작업을 맡기면 코드를 짜서 PR로 돌려주는 OpenAI의 코딩 에이전트.', true),
  ('gemini-code', 'Gemini Code Assist', 'ai_code', 'overseas', 'https://codeassist.google', '구글 Gemini 기반의 무료 개인용 AI 코딩 도구.', true),
  ('base44', 'Base44', 'ai_code', 'overseas', 'https://base44.com', '말로 설명하면 DB 포함 앱을 만들어 주는 노코드 AI 빌더.', true),
  ('firebase-studio', 'Firebase Studio', 'ai_code', 'overseas', 'https://firebase.studio', '구글의 브라우저 기반 AI 풀스택 앱 개발 환경.', true),
  ('trae', 'Trae', 'ai_code', 'overseas', 'https://www.trae.ai', '바이트댄스의 무료 지향 AI 코드 에디터.', true),
  ('warp', 'Warp', 'ai_code', 'overseas', 'https://www.warp.dev', 'AI 에이전트를 내장한 차세대 터미널.', true),
  ('granola-ai', 'Granola', 'ai_meeting', 'overseas', 'https://www.granola.ai', '내 메모와 녹음을 합쳐 회의록을 완성하는 AI 노트패드.', true),
  ('notta', 'Notta', 'ai_meeting', 'overseas', 'https://www.notta.ai', '다국어 회의 녹음·전사·요약 서비스(한국어 지원).', true),
  ('read-ai', 'Read AI', 'ai_meeting', 'overseas', 'https://www.read.ai', '회의·메일·메신저를 아우르는 업무 요약 코파일럿.', true),
  ('circleback', 'Circleback', 'ai_meeting', 'overseas', 'https://circleback.ai', '회의에서 할 일·결정사항을 자동 추출하는 AI 회의록.', true),
  ('sovoro', '소보로', 'ai_meeting', 'domestic', 'https://sovoro.kr', '실시간 한국어 음성 자막 서비스(회의·강의·방송).', true),
  ('plaud', 'Plaud', 'ai_meeting', 'overseas', 'https://www.plaud.ai', '녹음 하드웨어와 연동되는 AI 회의·통화 요약 서비스.', true),
  ('chatbase', 'Chatbase', 'ai_marketing', 'overseas', 'https://www.chatbase.co', '내 문서·사이트를 학습시켜 만드는 고객상담 AI 챗봇 빌더.', true),
  ('creatify', 'Creatify', 'ai_marketing', 'overseas', 'https://creatify.ai', '상품 URL만 넣으면 광고 영상을 만들어 주는 AI.', true),
  ('arcads', 'Arcads', 'ai_marketing', 'overseas', 'https://www.arcads.ai', 'AI 배우로 UGC 스타일 광고 영상을 만드는 도구.', true),
  ('ocoya', 'Ocoya', 'ai_marketing', 'overseas', 'https://www.ocoya.com', 'SNS 콘텐츠 생성·예약 발행을 한 번에 하는 마케팅 AI.', true),
  ('vcat', '브이캣', 'ai_marketing', 'domestic', 'https://vcat.ai', '상품 URL로 광고 영상·배너를 자동 생성하는 국내 서비스.', true),
  ('gorgias', 'Gorgias', 'ai_marketing', 'overseas', 'https://www.gorgias.com', '이커머스 특화 AI 고객응대 헬프데스크.', true),
  ('crisp', 'Crisp', 'ai_marketing', 'overseas', 'https://crisp.chat', '채팅 위젯·챗봇·공유 인박스를 갖춘 고객 메시징 플랫폼.', true),
  ('gumloop', 'Gumloop', 'ai_auto', 'overseas', 'https://www.gumloop.com', '드래그앤드롭으로 AI 업무 자동화를 만드는 노코드 툴.', true),
  ('bardeen', 'Bardeen', 'ai_auto', 'overseas', 'https://www.bardeen.ai', '브라우저 반복 작업을 자동화하는 AI 확장 프로그램.', true),
  ('activepieces', 'Activepieces', 'ai_auto', 'overseas', 'https://www.activepieces.com', '오픈소스 노코드 자동화 플랫폼(셀프호스팅 가능).', true),
  ('flowise', 'Flowise', 'ai_auto', 'overseas', 'https://flowiseai.com', 'LLM 에이전트·챗봇을 시각적으로 조립하는 오픈소스 빌더.', true),
  ('crewai', 'CrewAI', 'ai_auto', 'overseas', 'https://www.crewai.com', '여러 AI 에이전트를 팀처럼 굴리는 멀티에이전트 프레임워크.', true),
  ('genspark', 'Genspark', 'ai_auto', 'overseas', 'https://www.genspark.ai', '조사·제작·전화까지 대신하는 범용 AI 에이전트.', true),
  ('dalpha', '달파', 'ai_auto', 'domestic', 'https://dalpha.so', '기업 업무에 맞춘 AI 에이전트를 구축해 주는 국내 서비스.', true),
  ('browse-ai', 'Browse AI', 'ai_auto', 'overseas', 'https://www.browse.ai', '코딩 없이 웹사이트 데이터를 추출·모니터링하는 도구.', true),
  ('scispace', 'SciSpace', 'ai_research', 'overseas', 'https://scispace.com', '논문 검색·요약·질의응답을 돕는 연구 AI.', true),
  ('semantic-scholar', 'Semantic Scholar', 'ai_research', 'overseas', 'https://www.semanticscholar.org', '앨런AI연구소의 무료 AI 학술 검색 엔진.', true),
  ('researchrabbit', 'ResearchRabbit', 'ai_research', 'overseas', 'https://www.researchrabbit.ai', '논문 연결망을 시각화해 관련 연구를 찾아 주는 도구.', true),
  ('scite', 'Scite', 'ai_research', 'overseas', 'https://scite.ai', '인용이 지지인지 반박인지 분류해 주는 근거 검증 AI.', true),
  ('felo', 'Felo', 'ai_research', 'overseas', 'https://felo.ai', '출처를 보여 주는 다국어 AI 검색 엔진.', true),
  ('goover', '구버', 'ai_research', 'domestic', 'https://goover.ai', '주제를 등록하면 매일 브리핑을 만들어 주는 국내 AI 리서치 서비스.', true),
  ('wordvice-ai', 'Wordvice AI', 'ai_research', 'domestic', 'https://wordvice.ai', '논문·에세이 영문 교정에 특화된 국내 AI 교정기.', true),
  ('immersive-translate', 'Immersive Translate', 'ai_research', 'overseas', 'https://immersivetranslate.com', '웹·PDF를 원문 대조로 번역하는 브라우저 확장.', true),
  ('chatpdf', 'ChatPDF', 'ai_research', 'overseas', 'https://www.chatpdf.com', 'PDF를 업로드해 대화로 내용을 묻는 문서 AI.', true)
on conflict (id) do nothing;

-- 기존 등재 도구의 AI 분야 이동(0006의 vrew/typecast 선례): 딥브레인 AI STUDIOS는 영상 AI가 본질
update public.platforms set category_id = 'ai_video' where id = 'aistudios';
